- name: ensure php8.3 is installed
  apt:
    name:
      - php8.3-cli
      - php8.3-fpm
      - php8.3-zip
      - php8.3-ctype
      - php8.3-dom
      - php8.3-xml
      - php8.3-gd
      - php8.3-curl
      - php8.3-iconv
      - php8.3-intl
      - php8.3-imagick
      - php8.3-mbstring
      - php8.3-mysql
      - php8.3-bcmath
      - php8.3-soap
      - php8.3-xsl
      - php8.3-zip
      - php8.3-xdebug
  notify:
    - restart php-fpm

- name: xdebug remote enable
  blockinfile:
    dest: /etc/php/8.3/mods-available/xdebug.ini
    block: |
      xdebug.mode=debug
      xdebug.client_port=9000
      xdebug.discover_client_host=1
      xdebug.log_level=0
  notify:
    - restart php-fpm
